### ISSUE TITLE
test.py文件有错？

### ISSUE THREAD

**Issue by lindentao** [rfyiamcool/pyautoreload#1]
环境：python2.6
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import pyautoreload
  File "/usr/lib/python2.6/site-packages/pyautoreload/__init__.py", line 49
    done = {module.__name__}
                           ^
SyntaxError: invalid syntax

**Comment by rfyiamcool** [comment]
没问题的... python2.7

```
[ruifengyun@kd pyreload (master ✗)]$ python test.py
this c
reload c
this c
reload c
```
